# Generated by Django 2.2 on 2019-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field_of_study', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
